version: '3.8'

services:
  db:
    image: postgres:15
    container_name: starspydb
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./app
    context: .
    container_name: starspy-app
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./app:/app
      - ./app/data/exports:/app/data/exports

  nginx:
    image: nginx:latest
    container_name: starspy-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - app

volumes:
  postgres_data: